# 1. Introduction to Numpy 
Focus on NumPy arrays (ndarray), array creation, and basic attributes.

In [1]:
import numpy as np

In [2]:
# Creating numpy arrays

# From list 
x = np.array([1, 2, 3])
assert(x.ndim == 1)
assert(x.shape == (3,))
assert(x.size == 3)
assert(x.dtype == np.int64)
assert(x.itemsize == 8)
assert(x.nbytes == 24)

# Creating a range 
x = np.arange(10)
print("Range:", x)

# Creating a random list
one_dim = np.random.randint(0, 10, size=5)
print("Random one-dimensional:", one_dim)

two_dim = np.random.randint(0, 10, size=(5,2))
print("Random two-dimensional:\n", two_dim)

three_dim = np.random.randint(0, 10, size=(5,2,3))
print("Random three-dimensional:\n", three_dim)

Range: [0 1 2 3 4 5 6 7 8 9]
Random one-dimensional: [7 2 7 5 2]
Random two-dimensional:
 [[8 0]
 [6 2]
 [6 4]
 [7 8]
 [7 1]]
Random three-dimensional:
 [[[6 1 5]
  [4 8 2]]

 [[9 2 6]
  [5 0 6]]

 [[9 8 4]
  [9 6 1]]

 [[4 5 2]
  [6 9 0]]

 [[1 0 0]
  [1 2 5]]]


## Assessing single element

In [3]:
print(one_dim)
# Assessing single element
assert(one_dim[0] == 3)
assert(one_dim[-2] == 5)

[7 2 7 5 2]


AssertionError: 

In [ ]:
print(two_dim)
# Assessing single element
assert(two_dim[0, 0] == 4)
assert(two_dim[2, 1] == 8)
assert(two_dim[4, -1] == 2)
assert(two_dim[-2, -1] == 8)

[[4 6]
 [3 9]
 [7 8]
 [5 8]
 [9 2]]


In [ ]:
# Numpy array has a fixed type.
# Inserting a floating point lead to truncation
x = np.arange(5)
assert(x[3] == 3)
x[3] = 10.145
assert(x[3] == 10)
print(x)
assert(x.dtype == np.int64)

[ 0  1  2 10  4]


## Slicing

In [ ]:
# Single dimension
print(one_dim)
print(one_dim[:2]) # [3 7]
print(one_dim[1:]) # [7 3 5 9]
print(one_dim[1:3]) # [7 3]
print(one_dim[::2]) # [3 3 9]
print(one_dim[::-1]) # [9 5 3 7 3]
print(one_dim[3::-1]) # [5 3 7 3]
print(one_dim[3::-2]) # [5 7]
print(one_dim[::-2]) # [5 7]

[3 7 3 5 9]
[3 7]
[7 3 5 9]
[7 3]
[3 3 9]
[9 5 3 7 3]
[5 3 7 3]
[5 7]
[9 3 3]


In [ ]:
# Multi-dimensional
print(two_dim)
# two rows, one column
print(two_dim[:2, :1])
# all rows, every other column
print(two_dim[:, ::2])
# reverse subarray dimensions
print(two_dim[::-1, ::-1])
# first column
print(two_dim[:, 0])
# first row
print(two_dim[0, :])
print(two_dim[0])

[[4 6]
 [3 9]
 [7 8]
 [5 8]
 [9 2]]
[[4]
 [3]]
[[4]
 [3]
 [7]
 [5]
 [9]]
[[2 9]
 [8 5]
 [8 7]
 [9 3]
 [6 4]]
[4 3 7 5 9]
[4 6]
[4 6]


## Create copies of arrays

In [ ]:
# Array slices return views

x2 = np.arange(10)
x2_sub = x2[:2] # [0 1]
print(x2_sub)

x2_sub[0] = 99
print(x2) # [99 1 2 ... 9]

[0 1]
[99  1  2  3  4  5  6  7  8  9]


In [ ]:
# Creating copies of array

x2_copy = x2[:2].copy()
print(x2_copy) # [99 1]
x2_copy[0] = -1
print(x2) # [99 1 2 ... 9]
print(x2_copy) # [-1 1]

[99  1]
[99  1  2  3  4  5  6  7  8  9]
[-1  1]


In [ ]:
x3 = np.arange(9)
# Reshaping to a grid
print(x3.reshape([3, 3]))
# Reshaping to a row vector (reshape & newaxis)
print(x3.reshape([1, 9]))
print(x3[np.newaxis, :])
# Reshaping to a column vector (reshape & newaxis)
print(x3.reshape([9, 1]))
print(x3[:, np.newaxis])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 3 4 5 6 7 8]]
[[0 1 2 3 4 5 6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Array Concatenation and Splitting

In [ ]:
# Concatenate arrays
np.random.seed(0)
x = np.random.randint(0, 10, size = 2)
y = np.random.randint(0, 10, size = 3)
z = np.random.randint(0, 10, size = 1)
print(x)
print(y)
print(z)
print(np.concatenate([x, y, z]))

[5 0]
[3 3 7]
[9]
[5 0 3 3 7 9]


In [ ]:
# Concatenate two-dimensional arrays along the first axis (concatenate & vstack)
xs = np.random.randint(0, 10, size = 6).reshape((2, 3))
print(xs)
ys = np.random.randint(0, 10, size = 6).reshape((2, 3))
print(ys)
print(np.concatenate([xs, ys]))
print(np.vstack([xs, ys]))

[[3 5 2]
 [4 7 6]]
[[8 8 1]
 [6 7 7]]
[[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]]
[[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]]


In [ ]:
# Concatenate two-dimensional arrays long the second axis (concatenate & hstack)
print(np.concatenate([xs, ys], axis = 1))
print(np.hstack([xs, ys]))

[[3 5 2 8 8 1]
 [4 7 6 6 7 7]]
[[3 5 2 8 8 1]
 [4 7 6 6 7 7]]


In [ ]:
# Splitting an array
x = np.arange(10)
x1, x2, x3 = np.split(x, [2, 5])
print(x1) # [0 1]
print(x2) # [2 3 4]
print(x3) # [5 6 7 8 9]

[0 1]
[2 3 4]
[5 6 7 8 9]


In [ ]:
# Splitting two-dimensional array vertically (vsplit)
xs = np.arange(15).reshape([3, 5])
print(xs)

xs1, xs2 = np.vsplit(xs, [1])
print(xs1) # [[ 0  1  2  3  4]]
print(xs2) # [[ 5  6  7  8  9] [10 11 12 13 14]]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2 3 4]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# Splitting two-dimensional array horizontally (hsplit)
xs1, xs2 = np.hsplit(xs, [1])
print(xs1) # [[ 0 ] [ 5 ] [ 10 ]]
print(xs2) # [[ 1 2 3 4 ] [ 6 7 8 9 ] [ 11 12 13 14 ]]

[[ 0]
 [ 5]
 [10]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]
