# 2. Computation on NumPy Arrays: Universal Functions

In [1]:
import numpy as np

In [4]:
# Loop is inefficient

def compute_inverse(values):
    output = np.empty(len(values))
    for (i, v) in enumerate(values):
        output[i] = 1.0 / v

    return output

In [5]:
x = np.random.randint(1, 100, size=1_000_000)
%timeit compute_inverse(x)

2.59 s ± 121 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
# Vectorized operation is much faster
%timeit (1.0 / x)

983 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Advanced ufunc features

In [7]:
# Specifying outputs

x = np.arange(10)
y = np.empty(10)

np.log(x, out=y)
print(y)

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/var/folders/3f/xk17ccgx4cs52vytx7sf_j9c0000gn/T/ipykernel_53641/3392736474.py:6: RuntimeWarning: divide by zero encountered in log
  np.log(x, out=y)


In [12]:
# Aggregates

x = np.arange(1, 10)
print(np.add.reduce(x))
print(np.multiply.reduce(x))

print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

45
362880
[ 1  3  6 10 15 21 28 36 45]
[     1      2      6     24    120    720   5040  40320 362880]


In [14]:
# Outer product
x = np.arange(1, 10)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])